### ISSUE TITLE
Doesn’t work on 13.5

### ISSUE THREAD

**Issue by jankais3r** [PoomSmart/PencilPro#3]
Jailbroken 2020 iPad Pro with Unc0ver on 13.5. Still cannot interact with any of the finger-only elements using a Pencil 2.

**Comment by PoomSmart** [comment]
Such as?

**Comment by jankais3r** [comment]
I cannot pull the Dock from below, or enter multitasking. I also cannot use the Pencil to open Control Center or Notifications. I thought that these are the actions that were supposed to be enabled by this tweak.

**Comment by PoomSmart** [comment]
Those gestures (edge gestures) are special and I have not found a way to go around that. For Control Center and Notifications, I will look into it later. It seems to break starting from iOS 13.5

**Comment by PoomSmart** [comment]
The newest version now works with Control Center. Notifications, it already does work.
