### ISSUE TITLE
Found a way to pull out the dock and use all the multitasking gestures, and fix a bug with the control center

### ISSUE THREAD

**Issue by crapasanya** [PoomSmart/PencilPro#6]
All you need to do is turn on the magnification (or something like that, I don't know for sure, since my system is not English) in the accessibility settings and then double-tap the screen with three fingers to zoom out. The problem is that if you accidentally double-tap the screen with three fingers, you have to tap twice more

**Comment by PoomSmart** [comment]
Will add this to README. Thanks.
